[package]
name = "portgraph"
version = "0.1.1"
edition = "2021"

[lib]
bench = false
name = "portgraph"
path = "src/lib.rs"

[dependencies]
thiserror = "1.0.28"
pyo3 = { version = "0.16.5", optional = true, features = [
    "multiple-pymethods",
] }
bitvec = "1.0.1"

[features]
pyo3 = ["dep:pyo3"]

[dev-dependencies]
criterion = { version = "0.4.0", features = ["html_reports"] }
proptest = "1.1.0"
rstest = "0.12.0"

[[bench]]
name = "portgraph"
harness = false
