[package]
name = "portgraph"
version = "0.2.0"
edition = "2021"
rust-version = "1.61"

[lib]
bench = false
name = "portgraph"
path = "src/lib.rs"

[dependencies]
thiserror = "1.0.28"
pyo3 = { version = "0.18.1", optional = true, features = [
    "multiple-pymethods",
] }
bitvec = "1.0.1"
serde = { version = "1.0.152", features = ["derive"], optional = true}
proptest = { version = "1.1.0", optional = true }
rand = { version = "0.8.5", optional = true }

[features]
pyo3 = ["dep:pyo3"]
serde = ["dep:serde"]
proptest = ["dep:proptest", "dep:rand"]

[dev-dependencies]
criterion = { version = "0.4.0", features = ["html_reports"] }
rmp-serde = "1.1.1"
rstest = "0.16.0"

[[bench]]
name = "portgraph"
harness = false
