# Automatic changelog generation for rust projects

[workspace]
# Open the release PR as a draft
pr_draft = true

# Only create releases / push to crates.io after merging a release-please PR.
# This lets merge new crates to `main` without worrying about accidentally creating
# github releases.
#
# To trigger a release manually, merge a PR from a branch starting with `release-plz-`.
release_always = false

[changelog]

header = """# Changelog

"""
sort_commits = "oldest"
protect_breaking_commits = true

commit_parsers = [
    { message = "^feat", group = "New Features" },
    { message = "^fix", group = "Bug Fixes" },
    { message = "^docs", group = "Documentation" },
    { message = "^style", group = "Styling" },
    { message = "^refactor", group = "Refactor" },
    { message = "^perf", group = "Performance" },
    { message = "^test", group = "Testing" },
    { message = "^chore", group = "Miscellaneous Tasks", skip = true },
    { message = "^revert", group = "Reverted changes", skip = true },
    { message = "^ci", group = "CI", skip = true },
]
