name: Continuous integration

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main
  merge_group:
    types: [checks_requested]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  MIRIFLAGS: '-Zmiri-permissive-provenance' # Required due to warnings in bitvec 1.0.1

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: v0
      - name: Check formatting
        run: cargo fmt -- --check
      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Build docs
        run: cargo doc --no-deps --all-features
        env:
          RUSTDOCFLAGS: "-Dwarnings"

  miri:
    # Not required, we can ignore it for the merge queue check.
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install latest nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: v0-nightly
      - name: Run miri
        run: cargo miri test

  benches:
    # Not required, we can ignore it for the merge queue check.
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: v0
      - name: Build benchmarks with no features
        run: cargo bench --verbose --no-run --no-default-features
      - name: Build benchmarks with all features
        run: cargo bench --verbose --no-run --all-features

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.70, stable, beta, nightly]
    steps:
      - uses: actions/checkout@v3
      - id: toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Configure default rust toolchain
        run: rustup override set ${{steps.toolchain.outputs.name}}
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: v0-rust-${{ matrix.rust }}
      - name: Build with no features
        run: cargo build --verbose --no-default-features
      - name: Build with all features
        run: cargo build --verbose --all-features
      - name: Tests with no features
        run: cargo test --verbose --no-default-features
      - name: Tests with all features
        run: cargo test --verbose --all-features